import "jquery";
import "angular";
import "ovh-ui-angular";
import "angular-animate";
import "angular-ui-bootstrap";
import "angular-cookies";
import "angular-dynamic-locale";
// import "angular-i18n";
import "angular-messages";
import "angular-moment";
import "angular-resource";
import "angular-sanitize";
import "angular-strap";
import "angular-translate";
import "angular-translate-loader-partial";
import "angular-ui-router";
import "angular-ui-sortable";
import "angular-ui-validate";
// import "animate.css";
import "bootstrap";
// import "bootstrap-additions";
import "bs4";
import "d3";
import "es5-shim";
// import "flag-icon-css";
// import "font-awesome";
import "jquery.cookie";
import "jquery.scrollto";
import "json3";
import "lodash";
import "matchmedia-ng";
import "moment";
import "ng-slide-down";
import "urijs";
import "validator";
// import "ovh-ui-kit";
import "ovh-angular-a-disabled";
import "ng-at-internet";
import "at-internet-ui-router-plugin";
import "ovh-angular-toggleclass";
import "ovh-jquery-ui-draggable-ng";

// FIXME: bad main entry
import "ovh-angular-sidebar-menu/dist/ovh-angular-sidebar-menu.js";

import "ovh-angular-jquery-ui-droppable";
import "ovh-angular-manager-navbar";
import "ovh-angular-actions-menu";
import "ovh-angular-responsive-popover";
import "ovh-angular-jsplumb";
import "ovh-angular-checkbox-table";
import "ovh-common-style";
// import "ovh-manager-webfont";
import "ovh-angular-form-flat/dist/ovh-angular-form-flat.js";
import "ovh-angular-q-allsettled";
import "ovh-angular-slider";
import "ovh-angular-stop-event";
import "ovh-angular-user-pref";
import "ovh-angular-toaster";
import "ovh-angular-browser-alert";
import "ovh-angular-pagination-front";
import "ovh-angular-responsive-page-switcher";
import "ovh-angular-responsive-tabs";
import "ovh-angular-sso-auth";
import "ovh-angular-sso-auth-modal-plugin";
import "ovh-angular-swimming-poll";
import "ovh-angular-doc-url";
import "ovh-angular-module-status";
import "ovh-angular-otrs";
import "ovh-api-services";
import "angular-chart.js";
import "ovh-angular-list-view";
import "jsurl";
import "moment-duration-format";
